### ISSUE TITLE
A lot of models are not rendeding correctly

### ISSUE THREAD

**Issue by Dwite** [googlevr/poly-sample-android#2]
Most of the models don't render properly, any ideas of what library could be used for rendering?

**Comment by btco** [comment]
Are you using PolySampleAndroid or PolySampleARCore?

PolySampleAndroid should support most Blocks models, but the renderer is very simple so it's unlit and doesn't support textures.

PolySampleARCore only supports models that have a single texture due to the way the renderer is set up.

Even though the sample renderers are limited, the OBJ files should be compatible with most 3D libraries and engines, so once you download the OBJ and supporting MTL/texture files using the Poly API, you should be able to feed those into your own rendering pipeline.

**Comment by Dwite** [comment]
@btco PolySampleAndroid, well I was trying just to change ID for example to [elfFxSObt4X](https://poly.google.com/view/elfFxSObt4X) and it failed to render it correctly, okay if it just a sample of using API, but not the rendering, I think this issue is out of project scope.

**Comment by btco** [comment]
Exactly. That asset isn't a Blocks object. It's an uploaded object with a texture and it's well beyond the sample's rendering capabilities.

Like you said, this is just a sample of the API. The rendering logic is minimal and meant only to demonstrate the API.

Thanks!
